#include <pebble.h>
void show_menu(void);
void hide_menu(void);
void start_game(void);
void continueDialogue(void) ;
void hideChoices(void);
void presentChoices(void);
int currentText;
GBitmap *s_res_frame1_bmp;
GBitmap *s_res_frame2_bmp;
GBitmap *s_res_frame3_bmp;
bool grumpy;
int currChoice;
bool choiceActive;
bool gameStarted;
bool end;
bool grumpy;
bool honest;
bool normal;
bool chinese;
bool stay;
bool love;
static BitmapLayer * s_bitmaplayer_2;
static BitmapLayer * s_bitmaplayer_1;
static BitmapLayer * s_bitmaplayer_3;
static TextLayer * s_textlayer_2;
static TextLayer * s_textlayer_3;
static TextLayer * s_textlayer_1;
static TextLayer * s_textlayer_4;